"""empty message

Revision ID: 051ff9fa0e34
Revises: b83981604601
Create Date: 2023-12-15 11:23:52.023934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051ff9fa0e34'
down_revision = 'b83981604601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
